layout: 
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,  # 1段目
   12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  # 2段目
   24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,  # 3段目
   40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]  # 4段目

layers:
  - name: Default
    bindings:
      # 1段目
      - [A, MO(1), C, D, E, F, G, H, I, J, K, L]
      # 2段目
      - [M, N, O, P, Q, R, S, T, U, V, W, X]
      # 3段目
      - [Y, Z, N1, N2, N3, N4, N5, N6, N7, N8, N9, N0, ENTER, SPACE]
      # 4段目
      - [ESC, TAB, MINUS, EQUAL, LBKT, RBKT, BSLH, SEMI, QUOT, COMMA, DOT, NONE, NONE, NONE]

  - name: Layer 1
    bindings:
      # 1段目
      - [1, MO(1), 3, 4, 5, 6, 7, 8, I, J, K, L]
      # 2段目
      - [M, N, O, P, Q, R, S, T, U, V, W, X]
      # 3段目
      - [Y, Z, N1, N2, N3, N4, N5, N6, N7, N8, N9, N0, ENTER, SPACE]
      # 4段目
      - [ESC, TAB, MINUS, EQUAL, LBKT, RBKT, BSLH, SEMI, QUOT, COMMA, DOT, NONE, NONE, NONE]
