name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: minatomato1947/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config
